# Generated by Django 4.0.6 on 2022-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjectsapp', '0002_alter_project_options_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
