# Generated by Django 4.0.6 on 2022-07-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProjectsapp', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
