# Generated by Django 4.0.6 on 2022-07-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProjectsapp', '0007_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lang',
        ),
    ]
