# Generated by Django 4.0.6 on 2022-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjectsapp', '0008_remove_project_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
